### ISSUE TITLE
Server can't spawn a container

### ISSUE THREAD

**Issue by maslick** [mafintosh/docker-browser-server#2]
Using with docker-browser-console I get this while trying to start and connect to a docker container from the browser: 
```
Server is listening on port 8080
Spawning new container (w0s7qrj10m3x47vi)
Killing container (w0s7qrj10m3x47vi)
```
Any thoughts why the container gets killed right after it's created?

**Comment by maslick** [comment]
remedy: run docker-browser-server as root

**Comment by mafintosh** [comment]
Awesome!

**Comment by CrashyBang** [comment]
I am getting this issue to with or without sudo, any suggestions?
