### ISSUE TITLE
docker-browser-server to open container ports (?)

### ISSUE THREAD

**Issue by maslick** [mafintosh/docker-browser-server#3]
is it possible to map any specified ports inside the container to the host (analog of the -P flag in the docker CLI)?

```
sudo docker run -t -i -P ubuntu bash
```

E.g.
```
docker-browser-server -P ubuntu
```

**Comment by mafintosh** [comment]
whats your use-cause for this? it already maps 80 to an external port so you can just bind to that

**Comment by maslick** [comment]
for example I am running a server in the container, and I want to be able to connect to this server from a client application installed on another machine. now a container spawned by docker-browser-server does not expose any ports and is identical to: 

```
sudo docker run -i -t ubuntu
```

**Comment by mafintosh** [comment]
It exposes 80 already, https://github.com/mafintosh/docker-browser-server#expose-a-http-server - Do you need to expose something else besides that port?

**Comment by maslick** [comment]
imagine I am running a mysql database on port 3306 in the container

**Comment by mafintosh** [comment]
ah ok. you cannot currently do that but I could add an option what allow you configure this (like a `opts.configure` function that would work like this)

``` js
server('mafintosh/dev', {
  configure: function (opts) {
    opts.ports[someRandomPort] = 3306
  }
}
```

would that solve your problem?

**Comment by maslick** [comment]
Here I guess you are manually setting the host port (someRandomPort), which is equivalent to: 
```
sudo docker run -i -t -p someRandomPort:3306 ubuntu /bin/bash
```
This means that you cannot spawn more than 1 container. 
Is it possible to support this (it will take the port from the EXPOSE statement in the Dockerfile and assign a random port on the docker host):
```
sudo docker run -i -t -P ubuntu /bin/bash
```

**Comment by maslick** [comment]
@mafintosh, I suppose that should be implemented in docker-run.

**Comment by mafintosh** [comment]
by `someRandomPort` i mean you would use a random port for every container (similar to what we do here, https://github.com/mafintosh/docker-browser-server/blob/master/index.js#L47)

**Comment by maslick** [comment]
```someRandomPort ```should be random for every container, that's right. So that you can run more than one container on the host system (otherwise docker will fail to launch those).

**Comment by maslick** [comment]
@mafintosh yeah, I looked at the code, so you're exposing two container ports by default (80 and 8441). However, how will the container user know which ports on the host have been mapped to container ports 80 and 8441? (I can see it with ```docker ps``` on the host, but the user doesn't have access to it). Is it possible to set env variables for him?

It would be nice if you could specify other ports while starting docker-browser-server, e.g.:

```
docker-browser-server -P ubuntu
# this would map all ports specified in the container (Dockerfile) to random ports on the host
```

or 

```
docker-browser-server -P 3306 3307 3308 ubuntu    
 # this will map a set of container ports to random ports on the host
```

**Comment by mafintosh** [comment]
env vars seems like a great idea. like `PORT_3306 = the_real_port` ? I like the `-P` option as well.

**Comment by maslick** [comment]
Regarding env variables, I think we have $HOSTNAME and $CONTAINER_ID mixed up. Correct me if I'm wrong.

```
root@0529e78a3563:/home/dcdb$ env
HOSTNAME=0529e78a3563                                                                   
HOST=http://**lrpk1bhrtmg3nmi**.c.nds-devel.cosylab.com:8081                                  
TERM=xterm                                                                                
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                         
PWD=/home/dcdb                                                                            
PS1=\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]$                   
SHLVL=3                                                                                   
HOME=/root                                                                                
LESS=RS                                                                                   
CONTAINER_ID=lrpk1bhrtmg3nmi
PORT=80                                                                                   
_=/usr/bin/env
```

```
nds@ubuntu14-pmaslov:~$ sudo docker ps -sl
CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS              PORTS                                                      NAMES               SIZE
0529e78a3563        pmaslov/dcdb:latest   "/bin/sh -c /run-con   7 minutes ago       Up 7 minutes        5000/tcp, 0.0.0.0:37855->8441/tcp, 0.0.0.0:38545->80/tcp   sharp_hypatia
```

**Comment by maslick** [comment]
@mafintosh, ```PORT_3306=the_real_port``` will be fine
